version: 0.2

env:
  variables:
    JWT_SECRET: codebuild-test-secret-32-characters-long

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 20
    commands:
      - echo "▶ Install phase started"
      - chmod +x ./gradlew

  pre_build:
    commands:
      - echo "▶ Pre-build phase started"
      - ./gradlew clean build -x test

  build:
    commands:
      - echo "▶ Docker build started"
      - docker build -t springboot-app .

  post_build:
    commands:
      - echo "▶ Build completed successfully"


artifacts:
  files:
    - '**/*'
